/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es/components/avatar/index.mjs')['ElAvatar']
    ElButton: typeof import('element-plus/es/components/button/index.mjs')['ElButton']
    ElCheckbox: typeof import('element-plus/es/components/checkbox/index.mjs')['ElCheckbox']
    ElColorPicker: typeof import('element-plus/es/components/color-picker/index.mjs')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es/components/config-provider/index.mjs')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es/components/dialog/index.mjs')['ElDialog']
    ElDrawer: typeof import('element-plus/es/components/drawer/index.mjs')['ElDrawer']
    ElDropdown: typeof import('element-plus/es/components/dropdown/index.mjs')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es/components/dropdown/index.mjs')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es/components/dropdown/index.mjs')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es/components/empty/index.mjs')['ElEmpty']
    ElForm: typeof import('element-plus/es/components/form/index.mjs')['ElForm']
    ElFormItem: typeof import('element-plus/es/components/form/index.mjs')['ElFormItem']
    ElInput: typeof import('element-plus/es/components/input/index.mjs')['ElInput']
    ElOption: typeof import('element-plus/es/components/select/index.mjs')['ElOption']
    ElPopover: typeof import('element-plus/es/components/popover/index.mjs')['ElPopover']
    ElRadio: typeof import('element-plus/es/components/radio/index.mjs')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es/components/radio/index.mjs')['ElRadioGroup']
    ElRate: typeof import('element-plus/es/components/rate/index.mjs')['ElRate']
    ElSegmented: typeof import('element-plus/es/components/segmented/index.mjs')['ElSegmented']
    ElSelect: typeof import('element-plus/es/components/select/index.mjs')['ElSelect']
    ElSlider: typeof import('element-plus/es/components/slider/index.mjs')['ElSlider']
    ElSwitch: typeof import('element-plus/es/components/switch/index.mjs')['ElSwitch']
    ElTabPane: typeof import('element-plus/es/components/tabs/index.mjs')['ElTabPane']
    ElTabs: typeof import('element-plus/es/components/tabs/index.mjs')['ElTabs']
    ElTag: typeof import('element-plus/es/components/tag/index.mjs')['ElTag']
    ElTooltip: typeof import('element-plus/es/components/tooltip/index.mjs')['ElTooltip']
    ElUpload: typeof import('element-plus/es/components/upload/index.mjs')['ElUpload']
    RichTextEditor: typeof import('./src/components/RichTextEditor.vue')['default']
  }
}
